baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ink"
theme = "ink"
paginate = 5

copyright = "Â© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = "Crisp, minimal personal [blog theme for Hugo](https://github.com/knadh/hugo-ink)"

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/knadh/ink"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
